global:
  scrape_interval: 15s
  evaluation_interval: 30s
scrape_configs:
  - job_name: example-app
    static_configs:
      - targets: ["localhost:8080"]
        labels:
          app: example-app
#    relabel_configs:
#      - source_labels: [handler]
#        regex: ^found$
#        separator: ""
#        replacement: ""
#        action: keep




